# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    "aur_apps"
]

# Packages to be installed via the native package manager.
pkg_managers.system.pkgs = [
	"libreoffice-fresh",
	"ripgrep",
	"python-pipx",
	"wi",
	"most",
	"jq",
	"telegram-desktop",
	"go",
	"jdk-openjdk",
	"bat",
	"fd",
	"docker",
	"timeshift",
	"vlc",
	"seahorse",
	"bitwarden",
	"fzf",
	"fish",
	"obsidian",
	"font-manager",
	"yay",
	"zoxide",
	"gnome-tweaks",
	"network-manager-applet",
	"gnome-boxes",
	"baobab",
	"gnome-browser-connector",
	"git-delta",
	"fastfetch",
	"transmission-gtk",
	"jupyterlab",
	"lsd",
	"chezmoi",
	"kitty",
	"gparted",
	"vim",
	"fwupd",
	"gnome-logs",
	"gnome-firmware",
	"snapshot",
	"flatpak",
	"evolution"
]

# Packages to be installed via Flatpak.
pkg_managers.flatpak.pkgs = [
	"dev.geopjr.Collision",
	"com.github.GradienceTeam.Gradience",
	"org.localsend.localsend_app"
]

# Packages to be installed via Cargo.
pkg_managers.cargo.pkgs = [
]
