# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    "aur_apps"
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "libreoffice-fresh",
	"ripgrep",
	"python-pipx",
	"iw",
	"most",
	"jq",
	"telegram-desktop",
	"go",
	"jdk-openjdk",
	"bat",
	"fd",
	"docker",
	"timeshift",
	"vlc",
	"seahorse",
	"bitwarden",
	"fzf",
	"fish",
	"obsidian",
	"font-manager",
	"yay",
	"starship",
	"gimp",
	"zoxide",
	"gnome-tweaks",
	"network-manager-applet",
	"gnome-boxes",
	"baobab",
	"gnome-browser-connector",
	"git-delta",
	"fastfetch",
	"transmission-gtk",
	"jupyterlab",
	"lsd",
	"chezmoi",
	"kitty",
	"gparted",
	"vim",
	"fwupd",
	"gnome-logs",
	"gnome-firmware",
	"snapshot",
	"flatpak",
	"evolution"
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    "dev.geopjr.Collision",
	"com.github.GradienceTeam.Gradience",
	"flathub app.drey.Warp",
	"org.gnome.gitlab.somas.Apostrophe"
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
