[managers.system]
items = [
	"brave-bin",
	"pycharm-professional",
	"nautilus-admin-gtk4",
	"morewaita",
	"pokemon-colorscripts-git",
	"nnn-nerd",
	"informant",
	"pacseek-bin",
	"zotero-bin",
	"leetgo-bin",
	"proton-vpn-gtk-app",
	"gnome-shell-extension-dash-to-dock",
	"mutter-performance",
	"visual-studio-code-bin",
	"webcord-bin",
	"google-chrome",
	"miniconda3",
	"adw-gtk3",
	"lazydocker-bin",
	"pam-fprint-grosshack",
	"timeshift-autosnap",
	"ventoy-bin",
	"megasync-bin",
	"sublime-text-4",
]

