# --------------------------- #
#    Manager Configuration    #
# --------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put items, enter '#:?'.

# Example: add = "sudo apt install #:?"

add = "yay -S --needed --answerdiff None --answerclean None #:?" # Example: sudo apt install #:?
remove = "yay -Rns #:?" # Example: sudo apt remove #:?
sync = "sudo yay -Syy" # Example: sudo apt update
upgrade = "sudo yay -Su" # Example: sudo apt upgrade

plural_name = "system packages"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_args = BOOL: Can you supply many items as an argument? Example: 'sudo apt install git vim wget'

[config]
many_args = true
